# Conclusion {#sec-conclusion}

---
subtitle: "Evaluating the American Experiment with Today's Knowledge"
---

{{< include _data.qmd >}}

The US Constitution laid the foundations for centuries of stability and prosperity—for some, at least—but it is no longer compatible with American society. American-style systems concentrate broad powers in an ever-expanding executive that alternates control between two parties, so they perform best when voters are split into two main sides.[^conclusion-1] They struggle when voters become more divided since multiparty systems are not stable in these institutions.[^conclusion-2] If voting rights expansions or ideological rifts add more dimensions to politics, the country has to either sort itself back into two parties as the US did after the Civil Rights Era, or it descends into conflict as it did leading up to the Civil War.[^conclusion-3]

[^conclusion-1]: By American-style systems, I mean countries with a presidential form of government and a majoritarian election system.

[^conclusion-2]: Majoritarian elections tend to only produce multiparty systems in countries where an entire region is dominated by a minority, especially if that region has its own national identity and has been its own country in the past. These regions have distinct political cultures from the rest of the country, so regional parties are able to win seats in the legislature. In the US, Hawaii is the most likely state to have its own party, but it likely sees a greater advantage to working within the Democratic Party rather than as a tiny third party.

[^conclusion-3]: Leading up to the Civil War, Americans became split three ways: aside from the abolitionist unionists and pro-slavery secessionists, there were also many pro-slavery unionists and a few abolitionist secessionists. The Civil War was triggered by the presidential election of Abraham Lincoln, who was elected by a minority of the population. In a parliamentary system or a presidential system with proportional representation, a coalition of parties would have run the government rather than a minority party, so it is possible the dispute could have been resolved peacefully if the US had more European-style institutions. However, this could have just delayed a conflict that was bound to happen and in some sense had to happen in order to end slavery for good.

In diverse societies, American-style systems can only stabilize by shrinking the electorate to a more cohesive subset of the population. For most of American history, systems of race, class, and gender limited the electorate to a privileged voting class that fit well in a two-party system. The Constitution was mostly adequate for maintaining democracy *within* this class, which helped this group prosper and keep order over the country as a whole. Over the twentieth century, many more groups were brought into the voting class.[^conclusion-4] The two-party system is now stretched beyond its limits: the parties are at maximum capacity and can barely hold themselves together, yet they each represent a third of the population or less and let the rest go ignored. Technically, a wide range of groups have a seat at the table, but in practice the table is not big enough for all of them. The system has replaced disenfranchisement with disillusionment to narrow the amount of support it needs to maintain order.

[^conclusion-4]: Voting rights expansions and immigration influxes brought many more cultural minorities into the electorate, and a proliferation of political philosophies brought more ideological minorities as well.

The US has been due for a transition to a newer constitutional model for at least half a century. American-style systems with diversifying electorates can appear to be stable on the surface, but the mismatch between the electorate and the majoritarian institutions quietly brews tension for decades. The symptoms of this tension are low voter turnout, deepening polarization, widening economic inequality, social unrest, and growing authoritarianism. The tension continues to boil until the system crashes unless either an anti-democratic movement forces the electorate to fit the institutions (by limiting voting rights to a smaller class that they can sustain) or a pro-democratic movement forces the institutions to fit the electorate.

Countries in this situation typically have to adopt elements of proportional representation and parliamentary democracy to remain both free and stable. These reforms encourage multiparty systems and spread out power among several groups rather than concentrating it in one or two. Americans have resisted making this transition because the bedrock of their national identity is the Constitution—not just the document itself, but its model—and reconstructing the model might mean Americans have to reconstruct their whole identity. American politics is not so much polarized as it is paralyzed by a lack of willpower to adapt its institutions to the changing world.

Now that American democracy is under more pressure than it has ever faced since the Civil War, the time is right for the US to return to its long-retired role as the world's pioneers of democracy and reevaluate some of the foundational features of its institutions. The US could learn from the advancements in constitutional design made over the last two centuries while tweaking them to fit American culture. For example, the US could limit executive power by making the cabinet answer to Congress rather than the president, a method that emulates parliamentary democracy while retaining the familiar institutions of presidential systems.[^conclusion-5] Likewise, Congress could be elected with open-list proportional representation, a variant of a common multiparty electoral system. Most multiparty democracies use party-list proportional representation, but the open-list method would be more relatable to Americans since it retains the tradition of primary elections.

[^conclusion-5]: This violates the rule that the three branches must be run independently, which is the point. As [Chapter @sec-majority] and @sec-conc-4theories below discuss, the separation of powers into three independent branches is rarely an effective safeguard against tyranny and usually enables tyranny by concentrating too much power in a single person. Countries with only two independent branches (the legislature and the judiciary, since the executive is run by the legislature) are significantly more likely to be democratic and stable. This point is practically a law in the comparative politics literature, but it is usually discussed in terms of parliamentary/presidential systems instead of the separation of powers into two/three independent branches.

Proportional representation can be achieved through laws, but other problems are more deeply ingrained in the Constitution. The Senate's extreme malapportionment creates a permanent inequality of power that skews policy toward whichever party happens to be favored more by smaller states. The separation of executive and legislative powers into independent branches enables presidents to continuously gain more power, and the Electoral College enables them to cater to a smaller share of the population. The brief, unclear language of the Constitution allows it to be interpreted in whichever way is the most favorable to the political establishment. Over time, population shifts toward larger states have been exacerbating the inequality in the Senate and the Electoral College while ideological rifts have weakened Americans' shared understanding of their constitutional text.

Even if there was demand for constitutional reform, the Constitution has one of toughest amendment processes in the world.[^conclusion-6] Most other long-lasting constitutions are regularly amended so they can adjust to social pressures and resolve disputes over vague language, which is the main reason they have lasted so long. The US has survived by using court decisions rather than amendments to modernize its constitutional system. The official interpreter of the Constitution is a panel of nine elites, many of whom were chosen by presidents who lost the popular vote and then approved by senators representing a minority of the population. This has worked well for a surprisingly long time, but at some point the country will need a more democratic process for updating its institutions. The features of the Constitution that cripple the American political system the most are the ones that are explicit and leave little room for reinterpretation.

[^conclusion-6]: Three-fourths of states must ratify any amendment for it to be added to the Constitution. Most other countries do not have any thresholds over two-thirds.

After building up so much deferred maintenance to its institutions, the US will eventually need to hold a constitutional convention. Americans invented the constitutional convention, but they seem to have forgotten that it is even an option. Around the world, conventions are common tools for maintaining peace and democracy. They bring together elected representatives from every corner of society to renegotiate an institutional setup that the public can support. Holding a convention would open the door to conversations on solutions that can address the root of the problems with American politics for the long term.

## Revisiting the American constitutional model

Most of what we know about constitutional design suggests that the US has enjoyed exceptional stability and prosperity *despite* its Constitution, not because of it. Many of the basic theories informing its design have been debunked over the last century. American-style systems are twice as likely to be autocracies as countries with newer constitutional models. Globally, the US Constitution is now used more as a model of what *not* to do since newer models perform better. The document's key features that Americans attribute its success to—its lack of detail, separation of executive and legislative powers, equal representation of states in the Senate, and uniquely high obstacles to change—are the very features that usually give rise to short-lived, corrupt regimes. The US is an anomaly. It is the only country that has remained stable for centuries with a presidential system and a barely touched constitution built on so many unsupported assumptions.

The US is still a great place to live compared to most of the world, but it is quickly becoming more polarized, unequal, and corrupt than its peers. Its luck with an outdated constitution may be running out. I recognize that calling for a more critical eye on the Constitution could be seen as a futile or unpatriotic effort. The document is central to American political culture, and questioning its merits could delegitimize it and fuel the very forces that are destabilizing the country. But unrest is already brewing, and encouraging people to think more critically about how the Constitution itself cultivated this unrest can help draw attention to where the solutions lie. In the meantime, it is important for the Constitution to be seen as fully legitimate throughout the public conversation and any amendment processes. The main point of this dissertation is that the US should revise the Constitution *before* it loses legitimacy and destablizes the country.

### The four horsemen of the Constitution's design {#sec-conc-4theories}

The Constitution was built on several theories that either no longer apply or are contradicted by the patterns that have emerged worldwide over the last two centuries. This dissertation explores four theories that influenced the Constitution's design or were offered later to justify its design. They were discussed at the Constitutional Convention, in the Federalist Papers, or other writings of the document's authors. For each theory, I reviewed the literature for evidence corroborating it or casting doubt on it:

1.  **Madison’s theory of multiparty democracy:** James Madison theorized that larger, more diverse nations would develop multiparty systems (in today's words) while small, homogeneous nations would have fewer parties. For this reason, Madison felt comfortable that the US was safe from a tyranny of the majority. Today, we know that most presidential systems naturally develop two-party systems unless they elect their legislatures with proportional representation. Without this newer election system, presidential systems are easily prone to being run by a majority party that can invade on minorities' rights.

2.  **Montesquieu’s theory of separation of powers:** The philosopher Montesquieu theorized that separating legislative and executive powers would prevent corruption. The US was the first of many countries to experiment with this arrangement. These countries (presidential systems) usually result in a single leader holding broad powers, whereas countries where the legislature runs the executive (parliamentary systems) spread out power among a wider group of officials. Presidential systems are much more likely to be corrupt and unstable than parliamentary systems. Scholars disagree on whether this reflects correlation or causation, but we know that the separation of powers into three independent branches is rarely an effective check on power and often helps chief executives gain too much power.

3.  **Washington's theory of the Senate as a cooling saucer:** George Washington suggested that the Senate would filter out extremism and polarization from the House. Nowadays, the Senate fuels polarization more than it cools it. Over the last half century, population shifts toward larger states have made it easier for Republicans to control the Senate while catering to fewer and fewer people, letting the party skew policy farther away from the center. The Senate now becomes polarized more quickly than the House. The magnitude of the effect of the Senate's apportionment on polarization is unclear since it is difficult to study empirically.

4.  **Madisonian theory of constitutional endurance:** The conventional wisdom typically attributed to James Madison was that short, vague constitutions would be more stable. The opposite is true; most long-lasting constitutions are more specific and detailed. Shorter constitutions tend not to last as long because they invite more disagreements in interpretation. The US Constitution is the exception, not the rule. This is likely because the Supreme Court's reinterpretations of the Constitution have taken on the role that amendment processes serve in most other countries.

If the Framers of the Constitution had today's knowledge on these four theories alone, they likely would have (1) required proportional representation for congressional elections; (2) given Congress more authority over the executive branch, possibly even keeping a parliamentary model; (3) based the Senate's apportionment on population; and (4) made the text more specific, detailed, and easier to amend to prevent future conflict over vague language. Perhaps the Senate would not have changed since many Framers including James Madison and Alexander Hamilton were not thrilled about letting each state have equal representation; they agreed to it since it was the only way to appease small states into ratifying the Constitution. The Framers might have at least made the House the more powerful chamber to minimize the risks that come with such an inequitably apportioned upper chamber.

### Constitutional conventions: a forgotten tool for strengthening democracy

A major step toward reinvigorating American democracy would be to hold a constitutional convention. The US has not held one since 1787 even though the Constitution provides a mechanism for it. Thomas Jefferson suggested conventions should be held every two decades or so, and the average state has held at least four conventions for its own constitution.[^conclusion-7] Constitutional conventions bring together representatives from every corner of society to consider proposals to amend or rewrite their foundational document. They usually propose several amendments and rarely propose an entirely new constitution. To hold a convention for the US Constitution, two-thirds of states would need to call for it, as Article V of the Constitution states:

[^conclusion-7]: This is a rough figure based on Ballotpedia's [-@ballotpedia2] count of more 233 state-level constitutional conventions in US history. Dividing by the 50 current states, that averages to just over 4 conventions per state. This is not necessarily the best measure of the frequency at which states hold conventions because many states have been added over the years. Additionally, some states may hold conventions much more frequently than average, which skews the average upwards.

> ::: quote-orig
> The Congress, whenever two thirds of both Houses shall deem it necessary, shall propose Amendments to this Constitution, or, on the Application of the Legislatures of two thirds of the several States, shall call a Convention for proposing Amendments, which, in either Case, shall be valid to all Intents and Purposes, as Part of this Constitution, when ratified by the Legislatures of three fourths of the several States, or by Conventions in three fourths thereof, as the one or the other Mode of Ratification may be proposed by the Congress\[.\]
> :::
>
> ::: quote-modern
> Congress can propose amendments to this Constitution by a two-thirds vote in each chamber, or it can call a constitutional convention if requested by the legislatures of two-thirds of the states. In either case, amendments become fully part of the Constitution when ratified by the legislatures or state-level constitutional conventions of three-fourths of the states, whichever Congress specifies.
> :::

This is all the Constitution says about conventions, so Congress has broad authority to determine how a convention would work. On the least democratic end of the spectrum, a convention could follow the model of the Constitutional Convention of 1787, a closed-door assembly where each state gets one vote through a small number of delegates chosen by state politicians. On the other end, a convention could resemble more inclusive conventions used around the world today: delegates are directly elected by the public, each person (not state) has an equal vote, and public input is sought throughout the process.

Dozens of bills have been introduced in Congress proposing details for a constitutional convention. None passed, but they generally converged on a common framework. The Congressional Research Service summarized these patterns in a 2017 report [@crs2016]. By the 1990s, most bills proposed structuring the convention like the Electoral College, with one delegate per congressional district plus two delegates for each entire state. These delegates would all be directly elected by the voters. The vice president would preside over the convention until leaders are elected by the delegates. Congress can reject the convention's proposed amendments if they are beyond the scope of the subjects the convention can touch.

Although Congress has established these loose precedents for constitutional convention procedures, a wide range of options still exist since the Constitution places very few restraints on conventions. Conventions can have multiple types of delegates who are chosen through different processes to make sure that all groups in society are represented, including the ones that are more spread out geographically. Some delegates could be elected by congressional districts using plurality voting while others are elected nationwide through proportional representation. Randomly selected citizens and constitutional experts appointed by Congress could also hold seats.

The key advantage of assembling a convention over the alternatives—Congress proposing amendments on its own or the Supreme Court reinterpreting constitutional provisions—is that conventions can more actively involve the public, which in turn fosters a wider discussion of how to improve the Constitution. Voters would have to think about what types of amendments they might support, if any, before electing their delegates. These delegates would then serve as an entirely new type of elected official whose sole job is reforming the nation's institutions while the rest of the government continues to operate. These delegates can hold town halls and online forums to learn their constituents' preferences on institutional reform, which is not usually a top priority for general elected officials. Conventions bring a whole atmosphere of discussion around constitutions, helping leaders find a consensus that the public supports.

It is important to note that these benefits would only be realized if a convention is democratically elected. An elite-run convention in the style of 1787 would not offer much benefit over starting amendments in Congress and could backfire by helping powerful elites or factions rig the Constitution in their favor. Conventions that are more democratic come with minimal risks and typically only improve democracy and stability.[^conclusion-8] If a convention were held today, the public would probably need more time to warm up to amendments that address the deeper issues in the Constitution such as the Senate's built-in inequality and the presidency's continuous expansion of power. Even if a constitutional convention does not successfully pass any amendments, the process itself would start the national conversations on these issues and would remind people that change is possible, which could open the door to more reforms in the long term.

[^conclusion-8]: Constitutional conventions where every major group in society is fairly represented and participates in drafting revisions tend to see the greatest improvements to democracy in the years that follow [@eisenstadt2015].

Constitutional conventions are not just for writing new constitutions. The only one the US has ever held resulted in a new constitution, but around the world conventions often only amend the existing one. A new constitution would probably not pass anyway, nor would the American public agree to it. To dissuade concerns that a convention could crush the national spirit by questioning the legitimacy of the whole system, Congress can set limits on a convention's scope. It can be tasked with exploring amendments on a particular subject and can be prohibited from proposing amendments on certain sections or rewriting the whole document. The US should focus on reforming election systems for Congress and the president, limiting the Senate's power, limiting presidential power, and amending the amendment process itself to be more democratic.

## Designing a better constitution

Every society is different, and there is no one-size-fits-all formula for a constitution that could optimize outcomes in any scenario. Instead, each constitution has to be tailored for the individual needs and goals of its constituents. Now that we have centuries' worth of data on the effects of different choices in different contexts, learning about these patterns is both important and practical. This section presents an app I built which shows how constitutional amendments can affect a variety of outcomes in different contexts. More specific suggestions for amendments are discussed next.

### AI-driven constitutional design

The app below is a tool that can help observers and political actors design a constitution for a given society. First, users can specify geographic, cultural, and economic conditions of a country, and they can also select which outcomes are the most important to them. The app then projects the optimal institutional design for these conditions. Users can edit this design to see how these adjustments will affect 10 different outcomes ranging from democracy and political stability to income inequality and standard of living.

```{=html}
<style>
  iframe {height: 750px; width: 100%; overflow-y: hidden; margin-top: 30px;}
  @media (max-width: 843px) {iframe {height: 1320px}}
  #fig-const-design {margin: 40px 0;}
  .column-page-inset, iframe {margin-bottom: 0;}
</style>
```
::: {#fig-const-design}
::: column-page-inset
```{=html}
<iframe src="https://nmorse.shinyapps.io/const-design/"></iframe>
```
:::

**The display above should take a moment to load. If it doesn't, [click here](https://nmorse.shinyapps.io/const-design/).** This app lets users configure a constitution on the left to maximize the outcomes in the graph on the right. By default, the app is configured to the United States Constitution. Users can pick whether to use linear regression or random forests for predictions. Linear regression produces less accurate predictions but it is easier to see how the bars move upon changing constitutional features. The plot on the second tab shows variance importance measures from the random forests, and the tooltip also displays coefficients from the linear regression models. Predictions are based on a sample of more than 600 constitutions since 1789, although some data were imputed with the MICE algorithm. All data are from the most recent version of the constitution. For example, the data for the US Constitution specifies that the upper house of the legislature is directly elected (even though the Senate was not directly elected until the 17th amendment) and democracy data for the US is as of 2021.
:::

### Amendments that could strengthen democracy

The process of revising the Constitution is just as important as the product, possibly even more important. No single person, not even the Constitutionater, knows what the best constitution would look like. Instead, every group in society must be included in a fair process for negotiating over its provisions. Only then can a constitution emerge with the right balance of empirical support and popular support. While political science research offers many insights on which amendments could have the most positive effects on American politics, even the most proven reforms could struggle if they are unpopular. People have to respect a constitutional provision for it to be seen as legitimate and for elected leaders to execute it faithfully. Below are some constitutional revisions that the political science literature and this dissertation lend the most support to, but they may only work if people want them to work.

1.  **Require proportional representation in Congress.** Many countries with healthy multiparty systems mandate proportional representation in their constitution. They often state that elections for their legislature must be conducted "on the basis of proportional representation" or something along those lines. This could also be achieved through laws, but an amendment to the Constitution would make it harder to undo and therefore would preserve a multiparty system longer into the future.

2.  **Shift the Senate's powers to the House.** The Senate is one of the most unequally representative legislative bodies in the world, which throws off the balance of the whole political environment.[^conclusion-9] Although the idea that each state should be counted equally in at least one institution makes sense, in reality it does more harm than good for most people's lives. The Senate makes it easier for elites to control policy through a party that only represents a fraction of the population. However, the equal representation of states in the Senate cannot be amended unless every state agrees to it. An easier alternative would be to shift all of the powers that only the Senate has (e.g., approving executive and judicial appointments) to the House, making the House the upper chamber. The Senate could also be stripped of all of its powers, which would make it a ceremonial body and would effectively turn the House into a unicameral legislature.

3.  **Remove the Electoral College and use approval voting for presidential elections.** The Electoral College enables the president to govern without being held accountable to a majority of the population. A national popular vote with simple majority voting or ranked-choice voting would be fine, but approval voting would work best. As discussed in [Chapter @sec-majority], ranked-choice voting does not offer much improvement over simple majority voting and can be confusing, whereas approval voting is simple and effective.[^conclusion-10] Under approval voting, each voter can select as many candidates as they want. They do not have to pick just one (although they could) and they do not have to order their preferences. The candidate with the most votes—the highest approval of the population—wins.

4.  **Remove the presidential veto power.** The presidential veto was intended to only be used if the president believed a piece of legislation was unconstitutional. The first presidents used it sparingly, for this purpose alone [@watson1987]. Early on, though, the power to decide constitutionality became vested solely in the courts, so presidents began using vetoes (and the threat of vetoes) to advance their own political agenda [@prakash2003]. This is why presidents have such strong influence on legislation. Legislation should be left to Congress, as was originally intended. Removing the president’s veto power would significantly limit the president’s unilateral power over Congress.

5.  **Give Congress more power over the executive branch.** In presidential systems, the executive usually gains more and more power over time. This may be inevitable because a single person has many advantages over a whole body of people. Many countries have sustainably limited presidential power by shifting the authority to dismiss executive officials from the president to their legislature. This would make the US a semi-presidential system, specifically a *premier-presidential system*.[^conclusion-11] The cabinet would still be chosen by the president but would answer to Congress. The president's main roles would be to set the agenda, represent the nation abroad, run foreign policy, oversee the military, and take the lead during emergencies.

6.  **Add term limits for judges.** Federal judges serve for life or until they decide to retire. The Framers of the Constitution believed this was the best way to prevent judges from biasing their decisions around their own political goals after serving on the court. This is not worth the cost: lifetime judicial appointments enable presidents to impose their legacy decades into the future, impeding on future generations' right to govern themselves. A better solution is to limit judges to serving no more than, say, 20 years, after which they are provided with a hefty pension and are prohibited from participating in public affairs of any kind. Note that term limits are not advisable for legislatures like Congress, as discussed in Chapter 2.

7.  **Shift some administrative powers to juries.** Constitutional processes that are supposed to be independent of partisan politics—election administration, judicial appointments, and impeachments, to name a few—could be handled by committees of randomly selected citizens, a model known as sortition. Sortition offers the benefits of democracy without its dangers: juries represent the public better than elected bodies, jurors’ votes are not clouded by reelection interests, and their decisions are based on careful deliberation rather than politicized media consumption. Like judicial juries, administrative juries would be ad-hoc; each would assemble for a single purpose, taking anywhere from a few hours to a few weeks to deliberate. Certain types of decisions could be required by the Constitution or by law to be decided by juries,[^conclusion-12] although Congress, the president, and courts could also defer virtually any other kind of decision in their power to a jury.[^conclusion-13] The public could also convene a jury for a specific power if a petition reaches a certain threshold.[^conclusion-14]

8.  **Require public approval of the Constitution and amendments.** The Constitution has never been put up for a public vote, nor have any of its amendments. In a true republic, the people have the right not just to pick their leaders, but to pick the system itself. If anything, democratic accountability for the system is more important than democratic accountability for individual leaders. Most modern democracies and US states require their constitutions and amendments to pass a public vote, and the US would benefit from this practice too by amending its amendment process. It could allow for any future amendment to be ratified by a public referendum instead of state legislatures. The Constitution as a whole could also go up for a public vote of confidence every 20 to 40 years. If the people are not satisfied with it, then a constitutional convention could be assembled to propose amendments or draft a new constitution.

9.  **Restructure the document.** An unusual trait of the Constitution is that the Bill of Rights was drafted after the rest of the Constitution. Many constitutions begin with a bill of rights and then lay out the institutions designed to protect those rights. Starting with the institutions and leaving the rights to an addendum is like prescribing a medicine before making a diagnosis. Perhaps the Constitution would have been designed differently if the Framers had already established which rights they were designing it to protect.

10. **Modernize the language.** The Constitution was deliberately written in a style that ordinary people of the day could understand, using eighteenth-century colloquialisms rather than scholarly jargon or elitist legalese.[^conclusion-15] The English language has changed so much over the last couple hundred years that the Constitution is difficult for most people to read nowadays. The language of the Constitution will keep getting more distant from modern English and causing deeper and deeper disagreements in interpretation as time goes on. As a result, the court tasked with interpreting vague constitutional language is slowly losing legitimacy. These trends could become particularly dangerous in the coming years as Americans become more polarized on provisions such as the Second Amendment. If government is of the people, by the people, and for the people, then the people should be able to maintain a common understanding of their own governing document.

[^conclusion-9]: Presidents cannot win their party primaries unless their policy agendas can realistically pass the Senate; House members usually model their behavior on their counterparts in the Senate in the hopes of moving up; judges must be confirmed by the Senate to serve in courts.

[^conclusion-10]: Experiments usually show that ranked-choice voting lowers voter satisfaction with the election result [@cerrone2021] and approval voting raises it [@fishburn1988].

[^conclusion-11]: *Semi-presidential systems* are presidential systems with elements of parliamentary democracy. There are two main types. In *premier-presidential systems*, the president appoints cabinet officials but only the legislature can dismiss them. This has two main differences from standard presidentialism: (a) the president cannot fire top officials, and (b) the legislature can remove cabinet officials for political disagreements or poor job performance, not just for impeachable crimes. France is a good example of a premier-presidential system. Another type of semi-presidentialism is *president-parliamentary systems*, where both the president and the legislature can remove cabinet officials. Germany is the strongest example of a president-parliamentary system. Outside of Germany and a couple other countries, this model tends to perform worse than standard presidential systems, while premier-presidential systems tend to perform just as well as parliamentary systems [@sedelius2017].

[^conclusion-12]: Some examples: nominations for judges, election administrators, attorneys general, and other theoretically nonpartisan posts would be made by juries rather than governors and the president (with recommendations from parties and interest groups).

[^conclusion-13]: Some examples: the president could defer the decision on whether to veto a controversial piece of legislation to a jury. Congress could establish a precedent of deferring a final vote on the annual budget to a jury. If the Supreme Court finds that a ruling comes down to a question of morality rather than an interpretation of the law, it could defer that question to a jury.

[^conclusion-14]: Some examples: a publicly initiated jury could hold an impeachment hearing of an official if the House refuses to, decide whether to indict a person for a crime that a prosecutor refused to pursue, or force the Senate to vote on a bill that the majority leader refused to bring to the floor.

[^conclusion-15]: The Supreme Court discusses this in [United States v. Sprague](https://tile.loc.gov/storage-services/service/ll/usrep/usrep282/usrep282716/usrep282716.pdf), page 731.

The last two points are more general critiques of the Constitution as a whole and would not necessarily translate into a specific amendment. Because of the odd structure, outdated language, and long list of issues with the institutional design, one could argue that the Constitution needs to be rewritten altogether. At the same time, any one of the first eight ideas listed above would likely heal American democracy at least a little. The Constitution needs a breath of fresh air, a jolt of some kind, to renew its energy. It needs to be seen not just for what it is, but what it could be.

## It's not 1787 anymore

The simple, uncomfortable truth about the US Constitution is that it is not a particularly well designed constitution by today's standards. The Constitution now excels only at survival, to the point now where it sacrifices the rest of its objectives so it can survive longer. On those actual objectives, listed in the preamble, the Constitution performs more poorly than most similar countries' constitutions. It was innovative by 1700s standards, but the rest of the world has been making great strides in constitutional design over the last two centuries. Most countries have rewritten their constitutions within the last century, each time building on the lessons of the previous. Their political systems were based on scientific evidence of what works and what doesn't. The American political framework was based mainly on speculation since barely any evidence existed yet. Many of its prominent features are ineffective and counterproductive.

One of the most unpopular features of the Constitution is the Electoral College, but the document's problems go much deeper. The Electoral College has garnered more attention than most other issues in the Constitution because it has a straightforward problem and a straightforward solution. The Electoral College weights certain votes more than others, which violates the most fundamental standard of elections: *one person, one vote*. The president is elected unequally, so of course the president serves unequally. 

If we look a little deeper, we see that the Electoral College treats people unequally because its composition is based in part on the Senate, which treats people even more unequally. On average, a person from the bottom half of states by population has 5 times as much power through their senators as a person from the other half. A person from Vermont has 46 times as much power through their senators as a person from Texas. Equal representation of states means unequal representation of people. This has ripple effects throughout the government: all judges and top officials are appointed by presidents and confirmed by the Senate. Of the elected institutions in the federal government, the House is the only one that even attempts to treat each person equally, yet it is the least powerful. 

Most of the power in the government stems from elections that count people unequally, so most of the government serves unequally. Over time, any groups that happen to be overrepresented can skew policy in their favor, building up a snowball effect of increasingly unfair outcomes. People naturally use this advantage to gain more freedom for themselves at the expense of others' freedom. Society as a whole sees a net loss to freedom, simply because its Constitution does not treat each person equally. To make matters worse, the primary source of this inequality---the apportionment of the Senate---is the one feature of the Constitution that is prohibited from being amended unless every single state agrees to it.

In the United States, political inequality is built into the core of the system, codified in the Constitution. Not even economic inequality, or the economic system in general, is so strictly enforced. The Constitution is immortal, never to be questioned, never to fall. If a leader demanded the same treatment, they would rightfully be labeled a tyrant. If a leader imposed the same level of inequality, Americans would not stand for it. When a centuries-old document does these, they make excuses for it. This is precisely why a tyrannical system is even more dangerous than a tyrannical leader. It's easier to have faith in a bad system than it is to have faith in a bad leader. It's easier to rationalize a tyranny of the dead than it is to rationalize a tyranny of the living.

By the end of Trump’s presidency, a pandora’s box of crises were unleashed: violence had been tearing through the country, people couldn’t even agree on who won an election, the Capitol was sieged by extremists, public confidence in the government was drying up, the president had lost the respect of the world, and hundreds of thousands of people were dying from an out-of-control pandemic that most other governments contained more effectively. The United States was facing an oddly similar set of crises to what it faced in 1787—although 1787 didn’t have the widespread election disputes, the attempted coup, or the mismanaged pandemic.

Furthermore, Trump’s rise to power was the culmination of a perfect storm of structural problems, each stemming from an outdated constitution. If the Constitution had included incentives for more parties, Trump would not have been one of only two viable candidates in 2016. If the Electoral College followed a principle so simple as counting each person equally (which virtually every other presidential system follows), Trump would not have won. If the Constitution’s checks and balances actually worked, Trump would not have been able to maintain such a firm grip on power. Trump—and the chaos he brought—rose not in spite of the Constitution, but because of it. At the very least, a more modern constitution could have stopped him and numbed the recent wave of democratic erosion.

The Founding Fathers were not as attached to their creation as Americans are today. Many of them would be concerned, not proud, to learn of the Constitution's extraordinary longevity. They saw it not as a perfect, permanent law of the land, but as a flawed, shorter-term compromise that would eventually run into problems. We now know how to fix those problems based on centuries’ worth of data and experience around the world. But the mood is different these days. Americans only know how to point fingers at problems and cross their fingers for solutions. The fear that a constitutional convention would make matters worse has overshadowed the fact that if Americans don’t even *try* to come together and agree on a better system, they may never see one.

The Constitution is held to an unusually low bar. American politics has become rife with injustice, indifference, incompetence, greed, elitism, corruption, and violence. This is not what a well-functioning constitution looks like, and there is no need to wait until the collapse of civilization to take action. *This* is the moment in history to reevaluate the foundation of the system. When the country's forefathers faced similar problems to the current ones, many wanted to stick with the original constitution but ultimately decided that a good constitution was better than a permanent one. They didn’t need death and destruction to realize their constitution was failing. They were proactive enough to build a better system before the old one fell. They had the courage to peacefully reconstruct their institutions before they descended into chaos. Do we?
